services:
  aigis:
    image: ghcr.io/tea-party/aigis:main
    env_file: .env
    restart: always
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - /tmp/qdrant/data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO
